Added "Build release zip" GitHub Action
10up/publisher-media-kit pull request #114
Opened 2022-12-02 16:08 UTC by faisal-alvi

### Description of the Change
PR Adds "Build release zip" GitHub Action to generate the release zip before the actual release and Release Instructions are updated to test generated zip before shipping a release.

Closes #113

### How to test the Change
* Fork the repo, merged this workflow, and tested the ZIP locally.

### Changelog Entry
> Added - "Build release zip" GitHub Action.

### Credits

Props @faisal-alvi 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-12-04 22:40 UTC, peterwilsoncc requested changes
As noted inline, the composer file isn't needed.

2022-12-04 22:40 UTC, peterwilsoncc commented on .github/workflows/build-release-zip.yml
> +
Composer isn't required here as the only class file is manually loaded

https://github.com/10up/publisher-media-kit/blob/e2cb88b3fca861b884ec58244e48301e0908f409/publisher-media-kit.php#L37

It's not included in the WordPress.org version, see [the latest tag](https://plugins.trac.wordpress.org/browser/publisher-media-kit/tags/1.3.0).

I suspect this is because the path in cased incorrectly, it uses `blocks/BlockContext/Tabs.php` whereas the namespace is `Blocks\BlockContext`.

2022-12-04 22:40 UTC, peterwilsoncc commented on .github/workflows/build-release-zip.yml
> +        uses: 10up/action-wordpress-plugin-build-zip@stable
Nit: EOF line break would be lovely.

2022-12-05 10:42 UTC, faisal-alvi commented on .github/workflows/build-release-zip.yml
> +
The composer dependencies install step is removed. Please let me know if we should change the namespace path or keep it.

2022-12-05 22:13 UTC, peterwilsoncc commented on .github/workflows/build-release-zip.yml
> +
I opened #118 to figure out the best fix: change the folder path or change the namespace. I suggested the latter for reasons of case-sensitivity but would value your feedback there.

2022-12-05 22:15 UTC, peterwilsoncc approved these changes
LGTM, thank you!

Are you able to double check the generated file on your fork and self merge if everything looks good?

2022-12-06 09:10 UTC, faisal-alvi commented
@peterwilsoncc I checked the new [zip](https://github.com/faisal-alvi/publisher-media-kit/actions/runs/3628057266) and it now matches with the wp.org (`vendor` folder is not included), thank you!

_before (top) - after (bottom):_
![image](https://user-images.githubusercontent.com/25176325/205868815-27718d1c-5520-4ef0-9e31-ba13317cb942.png)

2022-12-06 09:15 UTC, merged