Cypress integration migrated to 11+
10up/publisher-media-kit pull request #121
Opened 2022-12-06 10:05 UTC by jayedul

### Description of the Change
Cypress integration migrated to 11+

Closes #112 

### How to test the Change

- Install NPM dependencies
- Run `npm run cypress:run` to test without GUI
- Run `npm run cypress:open` to test with GUI
- Check if tests pass successfully

### Changelog Entry

> Changed - Cypress integration migrated to 11+

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-12-07 09:59 UTC, faisal-alvi requested changes
@jayedul thanks for the work. I have left some comments below, mostly questions, can you please have a look.

Also, I'm facing a slow load issue of my `wp-env` setup locally, which is causing a timeout error + failure of the cypress test so I was not able to run the tests locally, trusting the pipeline results. 🤞🏻

2022-12-07 09:59 UTC, faisal-alvi commented on .gitignore
> +tests/cypress/videos
It would be better to have a new line at the end of the file.

2022-12-07 09:59 UTC, faisal-alvi commented on package.json
> +    "cypress:run": "CYPRESS_BASE_URL=http://localhost:8889/ cypress run --config-file tests/cypress/config.config.js",
why do we need to append `CYPRESS_BASE_URL=http://localhost:8889/`? I assume the script should work without this addition.

2022-12-07 09:59 UTC, faisal-alvi commented on tests/cypress/config.config.js
> +			`${__dirname}/integration/pmk-block-patterns.test.js`,
What if we use a global pattern something like:
`specPattern: '${__dirname}/integration/*.test.{js,jsx,ts,tsx}',`

This would reduce the effort of adding new test files in the future.

2022-12-07 09:59 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +		cy.wait(5000);
We should avoid the use of a `wait` (here and below), is there any specific reason behind using it? What if a server needs more than 5 seconds, our test will fail in that case too. We should think about an alternate solution.

2022-12-07 09:59 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +});
Seems like the spaces are removed and tabs, but that is causing inconsistency with other test files. Should we also use tabs there or keep using spaces here?

2022-12-07 10:00 UTC, faisal-alvi commented on package.json
> +    "cypress:run": "CYPRESS_BASE_URL=http://localhost:8889/ cypress run --config-file tests/cypress/config.config.js",
Seems like this is already done meanwhile I was reviewing.

2022-12-07 10:07 UTC, jayedul commented on tests/cypress/integration/pmk-block-patterns.test.js
> +		cy.wait(5000);
I pushed without it, and Github checks failed. Then added it to make page ready and worked as expected. I'm not totally determined to keep or remove it.

2022-12-07 10:08 UTC, jayedul commented on tests/cypress/integration/pmk-block-patterns.test.js
> +});
Oh, I guess it was done by code formatter.

2022-12-07 10:19 UTC, jayedul commented on tests/cypress/integration/pmk-block-patterns.test.js
> +		cy.wait(5000);
Another thing is the initial Gutenberg modal is not guaranteed to show up every time. Sometimes it doesn't. Even if it shows, it has a little delay after page load. So if the script passes the close modal action before modal appears, it blocks subsequent click actions since elements are covered by that modal.

2022-12-07 13:13 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +		cy.wait(5000);
@jayedul lets make a use of [Cypress Utilities for WordPress](https://github.com/10up/cypress-wp-utils), it provides a command to close this popup.

See: https://github.com/10up/cypress-wp-utils/blob/trunk/src/commands/close-welcome-guide.ts

For your reference, I have used this library in SLA (https://github.com/10up/simple-local-avatars/commit/2900aec8b0ec84b38bcae83067b5a752ef728b66.)

2022-12-08 16:06 UTC, jayedul commented
@faisal-alvi 
Now all tests passes successfully and suggested changes have been resolved.

2022-12-09 11:31 UTC, faisal-alvi approved these changes
Thanks for the work @jayedul 🚀

2022-12-09 11:39 UTC, merged