WP 6.2 compatibility update
10up/publisher-media-kit pull request #142
Opened 2023-04-06 07:42 UTC by jayedul

### Description of the Change
WP compatibility version upgraded to 6.2 and tests passed successfully.

Closes #141

### Changelog Entry

> Changed - WP compatibility version upgraded to 6.2

### Credits

Props @jayedul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-04-06 09:32 UTC, jayedul commented
Though it is WP 6.2 compatibility, I had to update cypress test script and utils library to pass the Github checks.

2023-04-07 10:54 UTC, faisal-alvi requested changes

2023-04-07 10:54 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +
```suggestion

```

2023-04-07 10:54 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +            } else if ( $body.find( '[aria-label="Publisher Media Kit"]' ).length > 0 ) {
```suggestion
            } else if ($body.find( '[aria-label="Publisher Media Kit"]' ).length > 0) {
```

2023-04-07 10:54 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +			}
```suggestion
                        cy.get('[aria-label="Publisher Media Kit"]').click();
            }
```

2023-04-07 10:54 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +			}
In all the test files, the spaces are used, so we should follow the same here.

2023-04-07 10:54 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +            } else if ( $body.find( '[aria-label="Publisher Media Kit"]' ).length > 0 ) {
For the sake of code consistency.

2023-04-07 10:56 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
>              }
```suggestion
            } else if ($body.find( '[aria-label="Publisher Media Kit"]' ).length > 0) {
                        cy.get('[aria-label="Publisher Media Kit"]').click();
            }
```

2023-04-07 10:59 UTC, faisal-alvi approved these changes

2023-04-07 11:27 UTC, merged