fix: add editor-style entrypoint
10up/publisher-media-kit pull request #178
Opened 2024-01-15 13:22 UTC by davisshaver

### Description of the Change

Checkout branch and build

Load New Post page with plugin enabled. Do not have SCRIPT_DEBUG enabled. Do not observe the 404.

Closes https://github.com/10up/publisher-media-kit/issues/174

### How to test the Change

### Changelog Entry

Fixed: Build editor-style entrypoint

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

2024-01-15 13:32 UTC, davisshaver commented
I could use some help with reviewing and verifying this fix. After looking at it more closely, it kind of seems like this was never working for either dev/debug or prod modes. So I wonder if we even need this stylesheet loaded?

2024-01-16 21:58 UTC, dkotter requested changes

2024-01-16 21:58 UTC, dkotter commented on includes/core.php
> +			'assets/css/admin/editor-style.css' :
So I was curious on the history here of why we were referencing a file that doesn't exist. What I found is that this function (`mce_css`) was added in the initial scaffolding of this plugin and at that point, there was a `assets/css/frontend/editor-style.css` file. Shortly after that, this file was deleted but the code here was not.

My opinion here is we should just delete this `mce_css` function all together. It has never done anything for us so I don't think there's any loss by removing it.

Alternatively, if we want to keep this around (it is supposed to load CSS for the TinyMCE editor, not sure how much we even support that in this particular plugin), I think instead of building a new CSS file (`assets/css/admin/editor-style.css` here), we can use the existing `admin-style.css` file, as that contains the code found in `editor-style.css`

2024-01-16 22:00 UTC, davisshaver commented on includes/core.php
> +			'assets/css/admin/editor-style.css' :
Thanks for reviewing @dkotter. Your explanation makes a lot of sense to me. I haven't noticed any functional issues with not having the stylesheet. I think removing the function altogether makes sense. If you agree I can update the PR accordingly.

2024-01-16 22:21 UTC, dkotter commented on includes/core.php
> +			'assets/css/admin/editor-style.css' :
Yeah, I would just remove it at this point. If we need/want to try styling the Classic Editor view, this is something we can bring back but since it hasn't ever actually been working, think it's easiest to just remove for now

2024-01-17 14:22 UTC, davisshaver commented on includes/core.php
> +			'assets/css/admin/editor-style.css' :
@dkotter Updated the PR

2024-01-17 17:52 UTC, dkotter approved these changes

2024-01-17 17:59 UTC, merged