Fix responsive issues of media kit page
10up/publisher-media-kit pull request #52
Opened 2021-12-20 05:53 UTC by mehidi258

Fix #40

2021-12-21 10:22 UTC, faisal-alvi requested changes
@mehidi258 thanks for the PR.

**Note:** The image in the [description](https://github.com/10up/publisher-media-kit/pull/52#issue-1084388630) shows the `5 column statics` section, however, the original issue #40 mentions the `Our packages` section.

**Change request:**

<img width="541" alt="pmk-cr-for-pr52" src="https://user-images.githubusercontent.com/25176325/146913822-2a13abe8-0cf3-4fe4-9f02-b430e146119c.png">

2021-12-21 10:31 UTC, faisal-alvi commented
@mehidi258 Please also make sure the changes are compatible with (and not breaking) the [supported themes](https://github.com/10up/publisher-media-kit#theme-compatibility).

2021-12-23 15:37 UTC, mehidi258 commented
@faisal-alvi Fixed

2021-12-24 10:26 UTC, faisal-alvi approved these changes

2022-01-04 15:45 UTC, merged