Fix audience profiles border width
10up/publisher-media-kit pull request #59
Opened 2022-01-07 17:41 UTC by mehidi258

Fix: #48 
![image](https://user-images.githubusercontent.com/34313754/148584465-2af2dd09-dd2c-4eb1-b48a-6ab4d274b7bd.png)

![image](https://user-images.githubusercontent.com/34313754/148584510-4542ec60-8742-4261-982e-60cb4b9b4d2f.png)

2022-01-10 08:25 UTC, Sidsector9 commented on assets/css/frontend/components/audience-profiles.css
> +		max-width: initial !important; /* !important to override base styles */
I'm able to achieve full width border without the use of `!important`. Adding it will only make it difficult to override the border style for an end user. Is there any use cases where this `!important` is necessary?

2022-01-17 18:24 UTC, jeffpaul commented
Tagging @faisal-alvi for input here as well

2022-01-18 05:54 UTC, faisal-alvi requested changes
@mehidi258 thank you, the borders are now full width but can you please check the "increase spacing" issue mentioned in https://github.com/10up/publisher-media-kit/issues/48#issue-1069261171 and fix it?

2022-01-18 05:54 UTC, faisal-alvi commented on assets/css/frontend/components/audience-profiles.css
> +		max-width: initial !important; /* !important to override base styles */
@Sidsector9 I've checked with other themes (TwentyTwentyOne, TwentyTwenty, etc.) and they require `!important`. And a few don't (StoreFront, etc.). So adding `!important` seems to be required.

2022-01-18 15:23 UTC, Sidsector9 submitted a review, later dismissed

2022-01-27 06:29 UTC, faisal-alvi commented
@mehidi258 can you please check my [previous comment](https://github.com/10up/publisher-media-kit/pull/59#pullrequestreview-854968907)?

2022-01-27 10:29 UTC, mehidi258 commented
> @mehidi258 can you please check my [previous comment](https://github.com/10up/publisher-media-kit/pull/59#pullrequestreview-854968907)?

@faisal-alvi Done and updated screenshot

2022-01-27 15:57 UTC, faisal-alvi approved these changes
@mehidi258 thanks for the changes. LGTM! :rocket:

![image](https://user-images.githubusercontent.com/25176325/151395235-609107fb-4ed4-4399-a543-65974b89b131.png)
[image link](https://www.screencast.com/t/OsfC5lnwhi5u)

2022-01-27 16:15 UTC, merged