PHP 8 compatibility
10up/publisher-media-kit pull request #75
Opened 2022-03-23 10:06 UTC by faisal-alvi

### Description of the Change

Upgrade the plugin to be compatible with the least supportive PHP v7.0 up to the PHP v8.1

### Verification Process

Make sure the Github actions are passing. Also, test the full plugin functionalities.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

> Security - Plugin made compatible up to PHP 8.1

### Credits

Props @faisal-alvi, @peterwilsoncc

2022-03-25 02:42 UTC, peterwilsoncc requested changes
Added some notes inline. 

Two questions, possibly because I am still learning the OSP ways, and a change request.

2022-03-25 02:42 UTC, peterwilsoncc commented on .github/workflows/lint.yml
> +        phpcs_bin_path: './vendor/bin/phpcs . --runtime-set testVersion 7.0-'
Why are you setting the testVersion in the command line rather than the phpcs.xml file?

2022-03-25 02:42 UTC, peterwilsoncc commented on includes/core.php
> +		include_once PUBLISHER_MEDIA_KIT_BLOCK_PATTERS . 'question-block.html';
It may be dependent on the environment config but HTML files included like this can be executed as PHP. As a proof of concept I `included_once`d this as `index.html` from my `wp-config.php` file.

```html
<?php

echo "This file is called index.html"; exit;
```

I'd revert the name changes, as a developer may put in a code sample/comment not expecting it to execute. An echo would be harmless but if they're noting down how to drop a table using wpdb, then it would be more problematic.

That poor future developer may be ourselves...

2022-03-25 02:42 UTC, peterwilsoncc commented on tests/cypress/integration/pmk-block-patterns.test.js
> +        cy.get( '[aria-label="Publisher Media Kit - Cover"] .block-editor-block-patterns-list__item-title' ).click({ force: true });
This seems unrelated to the PR.

It's minor and fine if it's needed. I just want to make sure it's intentional.

2022-03-25 03:06 UTC, faisal-alvi commented on includes/core.php
> +		include_once PUBLISHER_MEDIA_KIT_BLOCK_PATTERS . 'question-block.html';
Those HTML files just serve the block pattern HTML markup, hence, does not require any PHP code in them. I changed them from `.php ` to `.html` after receiving feedback from the bot [here](https://github.com/10up/publisher-media-kit/runs/5658972002?check_suite_focus=true).

As per your note, we should revert them back to `.php` (and possibly add `phpcs:ignore`)?

2022-03-25 03:08 UTC, faisal-alvi commented on tests/cypress/integration/pmk-block-patterns.test.js
> +        cy.get( '[aria-label="Publisher Media Kit - Cover"] .block-editor-block-patterns-list__item-title' ).click({ force: true });
true, it's unrelated but does not worth a separate PR.

2022-03-25 03:15 UTC, peterwilsoncc commented on includes/core.php
> +		include_once PUBLISHER_MEDIA_KIT_BLOCK_PATTERS . 'question-block.html';
Yeah, I think we should.

As we may add additional block patterns in the future, I'd exclude the rule in the directory within the phpcs config file.

```xml
<rule ref="Internal.NoCodeFound">
		<exclude-pattern>/includes/block-patterns/*.php</exclude-pattern>
</rule>
```

I think `Internal.NoCodeFound` is the correct sniff name, but the bot doesn't show it so you'll need to confirm. Making sure I haven't messed up the exclude pattern would be good too.

2022-03-25 03:20 UTC, faisal-alvi commented on .github/workflows/lint.yml
> +        phpcs_bin_path: './vendor/bin/phpcs . --runtime-set testVersion 7.0-'
We are instructed to use this file's content to match with the base file provided [here](https://docs.google.com/document/d/1r6WSXn22bOYfotDd9oyqf_CPsPXBGK2M1TfKDeKQ7Ew/edit#) (_Step 10 under "PHP Compatibility Scanning"_). However, I checked and found [this](https://github.com/PHPCompatibility/PHPCompatibility#testversion-in-the-ruleset-versus-command-line).

> In PHPCS 3.2.0 and lower, once you set the `testVersion` in the ruleset, you could not overrule it from the command-line anymore. Starting with PHPCS 3.3.0, a `testVersion` set via the command-line will overrule the `testVersion` in the ruleset.

2022-03-25 03:32 UTC, peterwilsoncc commented on .github/workflows/lint.yml
> +        phpcs_bin_path: './vendor/bin/phpcs . --runtime-set testVersion 7.0-'
I reckon it's safe to keep as is for now and we can check with Darin if there is a reason the command line was suggested.

Thanks for pointing me to the doc.

2022-03-25 13:16 UTC, faisal-alvi commented on .github/workflows/lint.yml
> +        phpcs_bin_path: './vendor/bin/phpcs . --runtime-set testVersion 7.0-'
sure, @dkotter please share your thoughts.

2022-04-08 13:10 UTC, faisal-alvi commented on .github/workflows/lint.yml
> +        phpcs_bin_path: './vendor/bin/phpcs . --runtime-set testVersion 7.0-'
@peterwilsoncc according to [this message](https://10up.slack.com/archives/C84M9AA06/p1648460113851159) from slack, we are using `testVersion X.X-` so that the test will run for all PHP versions X.X till the latest.

2022-04-10 23:12 UTC, peterwilsoncc reviewed
Code looks good, one note about an inconsistency.

2022-04-10 23:12 UTC, peterwilsoncc commented on composer.json
> +    "lint": "phpcs . --runtime-set testVersion 7.2-",
```suggestion
    "lint": "phpcs . --runtime-set testVersion 7.0-",
```

7.0 according to readme.txt

2022-04-11 05:40 UTC, peterwilsoncc approved these changes

2022-04-11 13:18 UTC, merged