Upgrade: `10up-toolkit` to `v4`
10up/publisher-media-kit pull request #85
Opened 2022-05-27 10:33 UTC by faisal-alvi

### Description of the Change

This PR upgrades the `10up-toolkit` to version 4.

### Alternate Designs

n/a

### Possible Drawbacks

n/a

### Verification Process

Plugin functionalities should work without fail.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Security - Upgrade `10up-toolkit` to `v4`

### Credits

Props @jeffpaul @faisal-alvi

2022-06-06 08:14 UTC, Sidsector9 requested changes
@faisal-alvi there is a conflict it seems. Can you resolve?

2022-06-20 11:21 UTC, faisal-alvi commented
A new dependabot alert related to `semver-regex` is found here: https://github.com/10up/publisher-media-kit/security/dependabot/30. This PR will hopefully fix this issue. cc: @Sidsector9

2022-06-21 15:20 UTC, Sidsector9 submitted a review, later dismissed

2022-06-21 15:20 UTC, Sidsector9 commented on package.json
> +    "eslint-plugin-react-hooks": "^2.5.0",
@faisal-alvi a lot of these seem to be dev dependencies, should we move them?

2022-06-22 10:48 UTC, faisal-alvi commented on package.json
> +    "eslint-plugin-react-hooks": "^2.5.0",
@Sidsector9 removed it (https://github.com/10up/publisher-media-kit/pull/85/commits/dc446b725b6f0f69b52f54eb2eac9764b63d7794) and now the Github action is failing again, it requires these dependencies in order to lint properly. I've added them in https://github.com/10up/publisher-media-kit/pull/85/commits/3fd6908c285f96dc2ebdb0bb33b7fc1a353b8b9f which had fixed the issue. Any suggestions?

2022-06-22 15:51 UTC, Sidsector9 commented on package.json
> +    "eslint-plugin-react-hooks": "^2.5.0",
What I meant is, dev dependencies were added under dependencies. We can just move them under dev dependencies.

2022-06-22 16:51 UTC, faisal-alvi commented on package.json
> +    "eslint-plugin-react-hooks": "^2.5.0",
Oh! I read `should we remove them?` instead of `should we move them?` 😄

2022-06-22 16:59 UTC, faisal-alvi commented
Over to you @Sidsector9

2022-06-22 17:31 UTC, Sidsector9 approved these changes

2022-06-22 17:37 UTC, merged